name: bundle_builder
on: push
jobs:
  build_bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Check out branch source
        uses: actions/checkout@v4

      - name: Run the bundle builder
        run: make bundle

      - name: List bundle files
        run: >
          cd build && ls
          unzip *.zip && ls
          find .
